language: node_js
node_js:
  - '8'
cache: yarn
install:
  - yarn install
jobs:
  include:
    - stage: Build and test
      script:
        - yarn install
        - yarn test
        - yarn build
    - stage: npm release
      script: yarn build:prod
      deploy:
        provider: npm
        email: '$NPM_EMAIL'
        api_key: '$NPM_TOKEN'
        skip_cleanup: true
        on:
          tags: true
branches:
  only:
    - master
    - /^v[0-9]+.*$/
